export const INDUSTRY_OPTIONS = [
  'Industrial Automation',
  'System Integration',
  'Controls Engineering',
  'Machine Building',
  'Manufacturing',
  'Industrial Engineering',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Process Engineering',
  'Rail & Transportation',
  'Aerospace',
  'Automotive',
  'Energy & Utilities',
  'Oil & Gas',
  'Renewable Energy',
  'Mining & Metals',
  'Water & Wastewater',
  'Food & Beverage',
  'Pharmaceuticals',
  'Chemicals',
  'Packaging',
  'Electronics',
  'Semiconductors',
  'Robotics',
  'OEM (Original Equipment Manufacturer)',
  'Panel Builder',
  'Software',
  'Information Technology',
  'Artificial Intelligence',
  'Cloud Services',
  'Cyber Security',
  'Telecommunications',
  'Electronics & Embedded Systems',
  'Digital Transformation',
  'IoT & IIoT',
  'Data & Analytics',
  'Engineering Consultancy',
  'Business Consultancy',
  'Legal Services',
  'Accounting & Finance',
  'Marketing & Advertising',
  'Recruitment',
  'Training & Education',
  'Research & Development',
  'Architecture',
  'Project Management',
  'Construction',
  'Building Services',
  'Facilities Management',
  'Real Estate',
  'Infrastructure',
  'Civil Engineering',
  'HVAC',
  'Utilities',
  'Healthcare',
  'Medical Devices',
  'Biotechnology',
  'Laboratories',
  'Life Sciences',
  'Transportation',
  'Logistics',
  'Supply Chain',
  'Warehousing',
  'Shipping',
  'Freight Services',
  'Rail',
  'Aviation',
  'Marine',
  'Retail',
  'E-Commerce',
  'Wholesale',
  'Consumer Goods',
  'Hospitality',
  'Travel & Tourism',
  'Food Services',
  'Government',
  'Local Authority',
  'Defence',
  'Education',
  'Universities',
  'Non-Profit',
  'Charity',
  'Public Sector',
  'Banking',
  'Insurance',
  'Investment Management',
  'Financial Services',
  'FinTech',
  'Agriculture',
  'Farming',
  'Food Production',
  'AgriTech',
  'Startup',
  'SME',
  'Holding Company',
  'Distributor',
  'Supplier',
  'Partner',
  'Other',
] as const;

export function splitIndustryValue(value: string): [string, string] {
  const parts = value
    .split(/\s*\|\s*|\s*,\s*/)
    .map((x) => x.trim())
    .filter(Boolean);
  return [parts[0] ?? '', parts[1] ?? ''];
}

export function joinIndustryValue(primary: string, secondary: string): string {
  const first = primary.trim();
  const second = secondary.trim();
  if (!first && !second) return '';
  if (!first) return second;
  if (!second || second === first) return first;
  return `${first} | ${second}`;
}
