ALTER SCHEMA public OWNER TO splendid_user;
GRANT ALL ON SCHEMA public TO splendid_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO splendid_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO splendid_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO splendid_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO splendid_user;
